### ISSUE TITLE
how used with codepen 

### ISSUE THREAD

**Issue by catafest** [halvves/shaderpen#1]
I try to used , but not working , see https://codepen.io/catafest/pen/LepObQ

**Comment by mmmerl** [comment]
@catafest - Oh man... my apologies. Looks like I have a typo in my readme 😬. I'll fix that now.

`new ShaderPen()` should do the trick for you.

...also it looks like the shader code you are trying to use employs some of Shadertoy's deeper features (channels etc...). Right now ShaderPen unfortunately only replicates a very spartan subset of the features seen in Shadertoy.

**Comment by mmmerl** [comment]
closed by: https://github.com/halvves/shaderpen/commit/b9a05492bd297305947b3b3df40b877ec4230f06
